version: '2'
services:
    sico-app:
        image: sico
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=dev,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://sico-mysql:3306/sico?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sico-mysql:
        extends:
            file: mysql.yml
            service: sico-mysql
